export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGSITER_SUCCESS = "REGSITER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const GET_RECOMMANDED_MOVIES_REQUEST = "GET_RECOMMANDED_MOVIES_REQUEST";
export const GET_RECOMMANDED_MOVIES_SUCCESS = "GET_RECOMMANDED_MOVIES_SUCCESS";
export const GET_RECOMMANDED_MOVIES_FAILURE = "GET_RECOMMANDED_MOVIES_FAILURE";
